---
abstract: 'easy access to any pastebin'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Nopaste
no_index:
  directory:
    - inc
    - t
requires:
  Browser::Open: 0
  Class::Load: 0
  Clipboard: 0
  Config::GitLike: 0.00
  File::Spec: 0
  File::Temp: 0
  Module::Pluggable: 0
  Moose: 0.74
  MooseX::Getopt: 0.17
  URI::Escape: 0
  WWW::Mechanize: 0
  WWW::Pastebin::PastebinCom::Create: 0
  perl: 5.8.3
resources:
  homepage: http://github.com/sartak/app-nopaste/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/sartak/app-nopaste.git
    web: http://github.com/sartak/app-nopaste/tree
version: 0.32
