---
abstract: 'easy access to any pastebin'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Nopaste
no_index:
  directory:
    - inc
    - t
requires:
  Module::Pluggable: 0
  Moose: 0.74
  MooseX::Getopt: 0.17
  WWW::Mechanize: 0
resources:
  homepage: http://github.com/sartak/app-nopaste/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sartak/app-nopaste.git
version: 0.17
