---
abstract: 'easy access to any pastebin'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Nopaste
no_index:
  directory:
    - inc
    - t
requires:
  Browser::Open: 0
  Class::Load: 0
  Clipboard: 0
  File::Spec: 0
  File::Temp: 0
  Getopt::Long::Descriptive: 0.090
  JSON: 0
  Module::Pluggable: 0
  URI::Escape: 0
  WWW::Mechanize: 0
  WWW::Pastebin::PastebinCom::Create: 0
  perl: 5.8.3
resources:
  homepage: https://github.com/sartak/app-nopaste/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sartak/app-nopaste.git
version: 0.91
