use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Shawn
Moore
sartak
Karen
Etheridge
ether
code
Thomas
Sibley
trs
François
Gannaz
francois
tom
Justin
Hunter
justin
Ricardo
Signes
rjbs
Kevin
Falcone
kevin
Zoffix
Znet
cpan
David
Golden
dagolden
Sergey
Romanov
complefor
Rafael
Kitover
rkitover
Ævar
Arnfjörð
Bjarmason
avarab
Arthur
Axel
fREW
Schmidt
frioux
Сергей
Романов
sromanov
Bremner
bremner
Graham
Knop
haarg
Jason
Mills
jmmills
Jesse
Luehrs
doy
John
Goulah
jgoulah
github
Maximilian
Gass
mxey
Sebastian
Paaske
Tørholm
Eckankar
tsibley
Yuval
Kogman
nothingmuch
gregor
herrmann
gregoa
jluehrs2
vti
viacheslav
lib
App
Nopaste
Service
Codepeek
Snitch
Command
Ubuntu
PastebinCom
Debian
Pastie
Gist
ssh
Shadowcat
