use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Shawn
Moore
sartak
code
Karen
Etheridge
ether
Thomas
Sibley
tsibley
François
Gannaz
francois
Ricardo
Signes
rjbs
Justin
Hunter
justin
Kevin
Falcone
kevin
Zoffix
Znet
cpan
David
Golden
dagolden
Rafael
Kitover
rkitover
Sergey
Romanov
complefor
Jesse
Luehrs
doy
Arthur
Axel
fREW
Schmidt
frioux
יובל
קוג
Yuval
Kogman
nothingmuch
Darian
Anthony
Patrick
dap
Bremner
bremner
Graham
Knop
haarg
Jason
Mills
jmmills
John
Goulah
jgoulah
Maximilian
Gass
mxey
Sebastian
Paaske
Tørholm
Eckankar
gregor
herrmann
gregoa
vti
viacheslav
Ævar
Arnfjörð
Bjarmason
avarab
Сергей
Романов
sromanov
lib
App
Nopaste
Command
Service
Codepeek
Debian
Gist
PastebinCom
Pastie
Shadowcat
Snitch
Ubuntu
ssh
